default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  host: <%= ENV['DATABASE_HOST'] %>
development:
  <<: *default
test:
  <<: *default
  database: <%= ENV['DATABASE_TEST_NAME'] %>
production:
  <<: *default
